
package com.revature.web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HeroService", targetNamespace = "http://service.tourofheroes.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HeroService {


    /**
     * 
     * @return
     *     returns java.util.List<com.revature.web.Hero>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllHeroes", targetNamespace = "http://service.tourofheroes.revature.com/", className = "com.revature.web.GetAllHeroes")
    @ResponseWrapper(localName = "getAllHeroesResponse", targetNamespace = "http://service.tourofheroes.revature.com/", className = "com.revature.web.GetAllHeroesResponse")
    @Action(input = "http://service.tourofheroes.revature.com/HeroService/getAllHeroesRequest", output = "http://service.tourofheroes.revature.com/HeroService/getAllHeroesResponse")
    public List<Hero> getAllHeroes();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addHero", targetNamespace = "http://service.tourofheroes.revature.com/", className = "com.revature.web.AddHero")
    @ResponseWrapper(localName = "addHeroResponse", targetNamespace = "http://service.tourofheroes.revature.com/", className = "com.revature.web.AddHeroResponse")
    @Action(input = "http://service.tourofheroes.revature.com/HeroService/addHeroRequest", output = "http://service.tourofheroes.revature.com/HeroService/addHeroResponse")
    public void addHero(
        @WebParam(name = "arg0", targetNamespace = "")
        Hero arg0);

}
